version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: news
      POSTGRES_DB: AI_NEWS
    ports:
      - "5432:5432"
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database", "update"]

