// This file is auto-generated by TanStack Router

import { createFileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SinglePostComponentImport = createFileRoute('/single-post')()
const ThreadsComponentImport = createFileRoute('/threads')()
const SubmitComponentImport = createFileRoute('/submit')()
const NewComponentImport = createFileRoute('/new')()
const EditComponentImport = createFileRoute('/edit')()
const CommentsComponentImport = createFileRoute('/comments')()
const IndexComponentImport = createFileRoute('/')()

// Create/Update Routes

const SinglePostComponentRoute = SinglePostComponentImport.update({
  path: '/single-post',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/single-post.component'),
    'component',
  ),
})

const ThreadsComponentRoute = ThreadsComponentImport.update({
  path: '/threads',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/threads.component'),
    'component',
  ),
})

const SubmitComponentRoute = SubmitComponentImport.update({
  path: '/submit',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/submit.component'),
    'component',
  ),
})

const NewComponentRoute = NewComponentImport.update({
  path: '/new',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/new.component'),
    'component',
  ),
})

const EditComponentRoute = EditComponentImport.update({
  path: '/edit',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/edit.component'),
    'component',
  ),
})

const CommentsComponentRoute = CommentsComponentImport.update({
  path: '/comments',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/comments.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/comments': {
      preLoaderRoute: typeof CommentsComponentImport
      parentRoute: typeof rootRoute
    }
    '/edit': {
      preLoaderRoute: typeof EditComponentImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      preLoaderRoute: typeof NewComponentImport
      parentRoute: typeof rootRoute
    }
    '/submit': {
      preLoaderRoute: typeof SubmitComponentImport
      parentRoute: typeof rootRoute
    }
    '/threads': {
      preLoaderRoute: typeof ThreadsComponentImport
      parentRoute: typeof rootRoute
    }
    '/single-post': {
      preLoaderRoute: typeof SinglePostComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  CommentsComponentRoute,
  EditComponentRoute,
  NewComponentRoute,
  SubmitComponentRoute,
  ThreadsComponentRoute,
  SinglePostComponentRoute,
])
